//! Generated by `mb art atlas sprites`: source rects in assets/sprites.png texels, [x, y, w, h].
#![allow(dead_code)]
pub const POLE: [f32; 4] = [2.0, 2.0, 29.0, 300.0];
/// Where the trimmed rect sits in the original 32×300 image.
pub const POLE_OFFSET: [f32; 2] = [1.0, 0.0];
pub const POLE_SIZE: [f32; 2] = [32.0, 300.0];
pub const HILLS: [f32; 4] = [33.0, 2.0, 622.0, 200.0];
/// Where the trimmed rect sits in the original 720×200 image.
pub const HILLS_OFFSET: [f32; 2] = [49.0, 0.0];
pub const HILLS_SIZE: [f32; 2] = [720.0, 200.0];
pub const SUN: [f32; 4] = [657.0, 2.0, 128.0, 128.0];
/// Where the trimmed rect sits in the original 128×128 image.
pub const SUN_OFFSET: [f32; 2] = [0.0, 0.0];
pub const SUN_SIZE: [f32; 2] = [128.0, 128.0];
pub const MEADOW: [f32; 4] = [2.0, 304.0, 720.0, 93.0];
/// Where the trimmed rect sits in the original 720×120 image.
pub const MEADOW_OFFSET: [f32; 2] = [0.0, 13.0];
pub const MEADOW_SIZE: [f32; 2] = [720.0, 120.0];
pub const TOMATO_0: [f32; 4] = [724.0, 304.0, 92.0, 92.0];
/// Where the trimmed rect sits in the original 92×92 image.
pub const TOMATO_0_OFFSET: [f32; 2] = [0.0, 0.0];
pub const TOMATO_0_SIZE: [f32; 2] = [92.0, 92.0];
pub const TOMATO_2: [f32; 4] = [818.0, 304.0, 92.0, 92.0];
/// Where the trimmed rect sits in the original 92×92 image.
pub const TOMATO_2_OFFSET: [f32; 2] = [0.0, 0.0];
pub const TOMATO_2_SIZE: [f32; 2] = [92.0, 92.0];
pub const TOMATO_1: [f32; 4] = [912.0, 304.0, 92.0, 91.0];
/// Where the trimmed rect sits in the original 92×92 image.
pub const TOMATO_1_OFFSET: [f32; 2] = [0.0, 0.0];
pub const TOMATO_1_SIZE: [f32; 2] = [92.0, 92.0];
pub const BLANKET: [f32; 4] = [2.0, 399.0, 232.0, 88.0];
/// Where the trimmed rect sits in the original 520×88 image.
pub const BLANKET_OFFSET: [f32; 2] = [144.0, 0.0];
pub const BLANKET_SIZE: [f32; 2] = [520.0, 88.0];
pub const JELLY_2: [f32; 4] = [236.0, 399.0, 88.0, 88.0];
/// Where the trimmed rect sits in the original 88×88 image.
pub const JELLY_2_OFFSET: [f32; 2] = [0.0, 0.0];
pub const JELLY_2_SIZE: [f32; 2] = [88.0, 88.0];
pub const JELLY_0: [f32; 4] = [326.0, 399.0, 87.0, 88.0];
/// Where the trimmed rect sits in the original 88×88 image.
pub const JELLY_0_OFFSET: [f32; 2] = [0.0, 0.0];
pub const JELLY_0_SIZE: [f32; 2] = [88.0, 88.0];
pub const JELLY_1: [f32; 4] = [415.0, 399.0, 87.0, 88.0];
/// Where the trimmed rect sits in the original 88×88 image.
pub const JELLY_1_OFFSET: [f32; 2] = [0.0, 0.0];
pub const JELLY_1_SIZE: [f32; 2] = [88.0, 88.0];
pub const CLOUD_0: [f32; 4] = [504.0, 399.0, 160.0, 86.0];
/// Where the trimmed rect sits in the original 160×96 image.
pub const CLOUD_0_OFFSET: [f32; 2] = [0.0, 5.0];
pub const CLOUD_0_SIZE: [f32; 2] = [160.0, 96.0];
pub const TOAST: [f32; 4] = [666.0, 399.0, 132.0, 84.0];
/// Where the trimmed rect sits in the original 132×84 image.
pub const TOAST_OFFSET: [f32; 2] = [0.0, 0.0];
pub const TOAST_SIZE: [f32; 2] = [132.0, 84.0];
pub const MACARON_2: [f32; 4] = [800.0, 399.0, 119.0, 72.0];
/// Where the trimmed rect sits in the original 128×72 image.
pub const MACARON_2_OFFSET: [f32; 2] = [4.0, 0.0];
pub const MACARON_2_SIZE: [f32; 2] = [128.0, 72.0];
pub const MACARON_1: [f32; 4] = [2.0, 489.0, 112.0, 72.0];
/// Where the trimmed rect sits in the original 128×72 image.
pub const MACARON_1_OFFSET: [f32; 2] = [8.0, 0.0];
pub const MACARON_1_SIZE: [f32; 2] = [128.0, 72.0];
pub const MACARON_0: [f32; 4] = [116.0, 489.0, 109.0, 72.0];
/// Where the trimmed rect sits in the original 128×72 image.
pub const MACARON_0_OFFSET: [f32; 2] = [9.0, 0.0];
pub const MACARON_0_SIZE: [f32; 2] = [128.0, 72.0];
pub const CHEESE: [f32; 4] = [227.0, 489.0, 168.0, 68.0];
/// Where the trimmed rect sits in the original 168×84 image.
pub const CHEESE_OFFSET: [f32; 2] = [0.0, 8.0];
pub const CHEESE_SIZE: [f32; 2] = [168.0, 84.0];
pub const CLOUD_1: [f32; 4] = [397.0, 489.0, 200.0, 62.0];
/// Where the trimmed rect sits in the original 200×80 image.
pub const CLOUD_1_OFFSET: [f32; 2] = [0.0, 9.0];
pub const CLOUD_1_SIZE: [f32; 2] = [200.0, 80.0];
pub const BAGUETTE: [f32; 4] = [599.0, 489.0, 222.0, 44.0];
/// Where the trimmed rect sits in the original 232×44 image.
pub const BAGUETTE_OFFSET: [f32; 2] = [5.0, 0.0];
pub const BAGUETTE_SIZE: [f32; 2] = [232.0, 44.0];
pub const LEAF: [f32; 4] = [823.0, 489.0, 19.0, 32.0];
/// Where the trimmed rect sits in the original 48×32 image.
pub const LEAF_OFFSET: [f32; 2] = [14.0, 0.0];
pub const LEAF_SIZE: [f32; 2] = [48.0, 32.0];
pub const PLATE: [f32; 4] = [2.0, 563.0, 340.0, 23.0];
/// Where the trimmed rect sits in the original 340×32 image.
pub const PLATE_OFFSET: [f32; 2] = [0.0, 4.0];
pub const PLATE_SIZE: [f32; 2] = [340.0, 32.0];
