//! `mb new <name>`: a new game crate from the maimbrain-game skill's
//! template/ (2D), template-3d/ (`--3d`) or one of its genre starter kits
//! (`--kit runner`, kits/<genre>/). Works signed out: the id and creator come
//! from `--id`/`--creator`, else the signed-in account, else a placeholder
//! that builds and previews but can't be published.

use std::path::Path;

macro_rules! template {
    ($dir:literal, $path:literal) => {
        include_str!(concat!(env!($dir), "/", $path))
    };
}

struct Template {
    /// (path in the crate, contents); `NAME` is replaced with the crate name.
    files: &'static [(&'static str, &'static str)],
    icon: &'static [u8],
}

const TEMPLATE_2D: Template = Template {
    files: &[
        ("Cargo.toml", template!("MB_TEMPLATE_DIR", "Cargo.toml")),
        ("manifest.toml", template!("MB_TEMPLATE_DIR", "manifest.toml")),
        ("src/lib.rs", template!("MB_TEMPLATE_DIR", "src/lib.rs")),
        ("src/sim.rs", template!("MB_TEMPLATE_DIR", "src/sim.rs")),
    ],
    icon: include_bytes!(concat!(env!("MB_TEMPLATE_DIR"), "/icon.png")),
};

const TEMPLATE_3D: Template = Template {
    files: &[
        ("Cargo.toml", template!("MB_TEMPLATE_3D_DIR", "Cargo.toml")),
        ("manifest.toml", template!("MB_TEMPLATE_3D_DIR", "manifest.toml")),
        ("src/lib.rs", template!("MB_TEMPLATE_3D_DIR", "src/lib.rs")),
        ("src/sim.rs", template!("MB_TEMPLATE_3D_DIR", "src/sim.rs")),
        ("src/scene.rs", template!("MB_TEMPLATE_3D_DIR", "src/scene.rs")),
    ],
    icon: include_bytes!(concat!(env!("MB_TEMPLATE_3D_DIR"), "/icon.png")),
};

/// A genre starter kit: a small, complete game (kits/<name>/ in the skill),
/// copied whole. In place it's a workspace member named `kit_<name>`.
pub struct Kit {
    pub name: &'static str,
    /// One line from its kit.toml: what it plays like.
    pub summary: &'static str,
    /// From its kit.toml: "2D", "2D + physics2d", "3D (mb3d 2)"…
    pub tech: &'static str,
    /// (path in the crate, bytes).
    pub files: &'static [(&'static str, &'static [u8])],
}

impl Kit {
    /// The crate name the kit has in place (`kit_tower_defense`).
    fn crate_name(&self) -> String {
        format!("kit_{}", self.name.replace('-', "_"))
    }
}

// `KITS` and `KIT_SCRIPTS`, generated by build.rs from the skill's kits/ and scripts/.
include!(concat!(env!("OUT_DIR"), "/kits.rs"));

/// Other names people reach for.
const KIT_ALIASES: &[(&str, &str)] = &[
    ("td", "tower-defense"),
    ("defense", "tower-defense"),
    ("quiz", "trivia"),
    ("puzzle", "match3"),
    ("match", "match3"),
    ("shmup", "shooter"),
    ("endless", "runner"),
    ("jumper", "runner"),
    ("stack", "stacker"),
    ("physics", "stacker"),
    ("racing", "racer"),
    ("driving", "racer"),
];

/// Finds a kit by name, ignoring case, `-` and `_`, or by alias.
pub fn find_kit(name: &str) -> Option<&'static Kit> {
    let key = |s: &str| s.to_ascii_lowercase().replace(['-', '_', ' '], "");
    let want = key(name);
    let want = KIT_ALIASES.iter().find(|(a, _)| key(a) == want).map_or(want, |(_, k)| key(k));
    KITS.iter().find(|k| key(k.name) == want)
}

/// The `mb kits` / `mb new --kit list` text.
pub fn kit_list() -> String {
    let mut s = String::from("Genre starter kits (complete, polished games to reskin and twist):\n\n");
    let w = KITS.iter().map(|k| k.name.len()).max().unwrap_or(0);
    let t = KITS.iter().map(|k| k.tech.len()).max().unwrap_or(0);
    // The most-asked-for genres first; kits not in the list after them.
    const ORDER: [&str; 7] = ["runner", "stacker", "shooter", "match3", "racer", "tower-defense", "trivia"];
    let mut kits: Vec<&Kit> = KITS.iter().collect();
    kits.sort_by_key(|k| ORDER.iter().position(|n| *n == k.name).unwrap_or(ORDER.len()));
    for k in kits {
        s += &format!("  {:w$}  {:t$}  {}\n", k.name, k.tech, k.summary);
    }
    s += "\nmb new --kit <kit> games/<name>    then read games/<name>/DESIGN.md (tuning knobs, \"Make it yours\")\n";
    s
}

/// Where the SDK comes from outside this monorepo.
const SDK_GIT: &str = "https://github.com/terracatta/maimbrain-kit";
/// Used when there's no `--id` and nobody is signed in.
const PLACEHOLDER_NAMESPACE: &str = "com.maimbrain.yourname";
const PLACEHOLDER_CREATOR: &str = "yourname";
/// How a kit's Cargo.toml points at the SDK in place (kits/<genre>/ under the skill).
const KIT_SDK_PATH: &str = "../../../../../sdk/maimbrain";
const GAME_SDK_PATH: &str = "../../sdk/maimbrain";

pub struct Options<'a> {
    pub three_d: bool,
    /// A genre starter kit's name (`runner`, `tower-defense`…), instead of a template.
    pub kit: Option<&'a str>,
    /// Explicit bundle id (reverse-DNS), overriding the account's namespace.
    pub id: Option<&'a str>,
    /// Explicit creator handle (with or without the leading @).
    pub creator: Option<&'a str>,
    /// (username, id namespace) from the server, if signed in.
    pub who: Option<(&'a str, &'a str)>,
    /// The starting identity (default: one at random).
    pub identity: Option<&'a str>,
    /// Download and bake the identity's fonts (needs the network the first time).
    pub bake_fonts: bool,
}

pub fn new_game(dir: &Path, opts: &Options) -> Result<(), String> {
    let name = dir.file_name().and_then(|n| n.to_str()).ok_or("give the game a directory name, e.g. mb new frogger")?;
    if !name.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_') || name.is_empty() {
        return Err(format!("{name:?}: use lowercase letters, digits and _ (it becomes the crate name and the id's last part)"));
    }
    let kit = match opts.kit {
        Some(k) => Some(find_kit(k).ok_or_else(|| format!("no kit called {k:?}.\n\n{}", kit_list()))?),
        None => None,
    };
    if kit.is_some() && opts.three_d {
        return Err("--3d and --kit don't mix: a kit is already 2D or 3D (mb kits lists them)".into());
    }
    if dir.exists() {
        return Err(format!("{} already exists", dir.display()));
    }
    let namespace = opts.who.map_or(PLACEHOLDER_NAMESPACE, |w| w.1);
    let id = opts.id.map_or_else(|| format!("{namespace}.{}", name.replace('_', "-")), str::to_string);
    let creator = opts.creator.map(|c| c.trim_start_matches('@')).or(opts.who.map(|w| w.0)).unwrap_or(PLACEHOLDER_CREATOR);
    // Inside the Maimbrain monorepo (games/<name>) the crate joins the workspace; elsewhere it's standalone.
    let in_monorepo = dir.parent().map(|p| p.join("../sdk/maimbrain/Cargo.toml").exists()).unwrap_or(false);

    // No two new games start alike: a template game gets a kit identity at
    // random (the skill's art-direction step replaces it with the game's own).
    // A kit keeps its own look.
    let identities = crate::fonts::identities();
    let nanos = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map_or(0, |d| d.subsec_nanos() as usize ^ d.as_secs() as usize);
    let identity = opts.identity.map(str::to_string).unwrap_or_else(|| identities.get(nanos % identities.len().max(1)).map_or("riso".into(), |i| i.0.clone()));
    // (path, bytes) as they'll be written.
    let mut files: Vec<(String, Vec<u8>)> = Vec::new();
    match kit {
        Some(kit) => {
            let from = kit.crate_name();
            for &(path, bytes) in kit.files {
                let bytes = match std::str::from_utf8(bytes) {
                    Ok(text) if is_text(path) => kit_text(path, text, &from, name).into_bytes(),
                    _ => bytes.to_vec(),
                };
                files.push((path.to_string(), bytes));
            }
            // Its tools/ import the skill's helpers; give the game its own copies.
            if files.iter().any(|f| f.0.starts_with("tools/") && f.0.ends_with(".py")) {
                for &(script, bytes) in KIT_SCRIPTS {
                    let path = format!("tools/{script}");
                    if !files.iter().any(|f| f.0 == path) {
                        files.push((path, bytes.to_vec()));
                    }
                }
            }
        }
        None => {
            let template = if opts.three_d { &TEMPLATE_3D } else { &TEMPLATE_2D };
            for &(path, text) in template.files {
                files.push((path.to_string(), text.replace("NAME", name).replace("__IDENTITY__", &identity).into_bytes()));
            }
            files.push(("icon.png".into(), template.icon.to_vec()));
        }
    }
    for (path, bytes) in &mut files {
        let text = || String::from_utf8_lossy(bytes).into_owned();
        match path.as_str() {
            "Cargo.toml" if !in_monorepo => *bytes = standalone_cargo(&text()).into_bytes(),
            "manifest.toml" => *bytes = manifest(&text(), &id, creator, &title_case(name)).into_bytes(),
            _ => {}
        }
    }
    // Check the manifest before writing anything (a bad --id fails here).
    let m = files.iter().find(|f| f.0 == "manifest.toml").map(|f| String::from_utf8_lossy(&f.1).into_owned()).unwrap_or_default();
    let parsed = mb_format::Manifest::parse(&m).map_err(|e| format!("manifest.toml: {e}"))?;
    let mut errors = Vec::new();
    parsed.check(&mut errors);
    if !errors.is_empty() {
        return Err(errors.join("; "));
    }

    std::fs::create_dir_all(dir.join("src")).map_err(|e| e.to_string())?;
    std::fs::create_dir_all(dir.join("assets")).map_err(|e| e.to_string())?;
    for (path, bytes) in &files {
        let p = dir.join(path);
        if let Some(parent) = p.parent() {
            std::fs::create_dir_all(parent).map_err(|e| format!("{path}: {e}"))?;
        }
        std::fs::write(&p, bytes).map_err(|e| format!("{path}: {e}"))?;
    }
    let what = match kit {
        Some(k) => format!("the {} kit, {}", k.name, k.tech),
        None if opts.three_d => "3D".into(),
        None => "2D".into(),
    };
    eprintln!("Created {} ({what}, id {id}, creator @{creator})", dir.display());
    if kit.is_none() {
        eprintln!("Starting identity: \"{identity}\", picked at random. Choose the game's own in the art-direction step (IDENTITY in src/lib.rs).");
        if opts.bake_fonts {
            if let Err(e) = crate::fonts::add_identity(dir, &identity) {
                eprintln!("warning: couldn't bake {identity}'s fonts ({e}); the game draws in the built-in fonts until you run `mb font add {} --identity {identity}`", dir.display());
            }
        }
    }
    if opts.who.is_none() && (opts.id.is_none() || opts.creator.is_none()) {
        eprintln!(
            "Not signed in, so manifest.toml has a placeholder id/creator. It builds, validates and previews as is; \
             before `mb publish`, run `mb login` and set id and creator to your namespace (`mb whoami`), \
             or pass --id and --creator to mb new."
        );
    }
    if kit.is_some() {
        eprintln!("Read {}/DESIGN.md first: how it plays, the tuning knobs, and \"Make it yours\".", dir.display());
    }
    eprintln!("Next: mb build {0}   then mb serve {0}", dir.display());
    Ok(())
}

/// Files whose text gets the crate name swapped (the rest are copied as is).
fn is_text(path: &str) -> bool {
    [".rs", ".toml", ".md", ".py", ".txt", ".json", ".wgsl"].iter().any(|e| path.ends_with(e))
}

/// A kit file's text for the new crate: the kit's crate name becomes the
/// game's, and Cargo.toml points at the SDK from games/<name>.
fn kit_text(path: &str, text: &str, from: &str, to: &str) -> String {
    let text = text.replace(from, to);
    if path != "Cargo.toml" {
        return text;
    }
    text.lines()
        .filter(|l| !l.trim_start().starts_with("# `mb new --kit`"))
        .map(|l| l.replace(KIT_SDK_PATH, GAME_SDK_PATH))
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}

fn standalone_cargo(text: &str) -> String {
    text.replace("edition.workspace = true", "edition = \"2024\"")
        .replace("version.workspace = true", "version = \"0.1.0\"")
        .replace("publish.workspace = true", "publish = false")
        .replace(&format!("path = \"{GAME_SDK_PATH}\""), &format!("git = \"{SDK_GIT}\""))
        + "\n# Standalone: not part of any parent workspace.\n[workspace]\n\n[profile.release]\nopt-level = \"s\"\nlto = true\ncodegen-units = 1\npanic = \"abort\"\n"
}

/// Sets the manifest's id, creator and name lines.
fn manifest(text: &str, id: &str, creator: &str, title: &str) -> String {
    text.lines()
        .map(|l| {
            if l.starts_with("id = ") {
                format!("id = \"{id}\"")
            } else if l.starts_with("creator = ") {
                format!("creator = \"@{creator}\"")
            } else if l.starts_with("name = ") {
                format!("name = \"{title}\"")
            } else {
                l.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}

fn title_case(s: &str) -> String {
    s.split('_')
        .filter(|w| !w.is_empty())
        .map(|w| w[..1].to_uppercase() + &w[1..])
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(tag: &str) -> std::path::PathBuf {
        let d = std::env::temp_dir().join(format!("mb-new-test-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&d);
        d
    }

    fn read_manifest(dir: &Path) -> mb_format::Manifest {
        mb_format::Manifest::parse(&std::fs::read_to_string(dir.join("manifest.toml")).unwrap()).unwrap()
    }

    fn opts<'a>() -> Options<'a> {
        Options { three_d: false, kit: None, id: None, creator: None, who: None, identity: None, bake_fonts: false }
    }

    #[test]
    fn signed_out_uses_a_placeholder_that_validates() {
        let root = scratch("out");
        let dir = root.join("frog_hop");
        new_game(&dir, &opts()).unwrap();
        let m = read_manifest(&dir);
        assert_eq!(m.id, "com.maimbrain.yourname.frog-hop");
        assert_eq!(m.creator, "@yourname");
        assert_eq!(m.name, "Frog Hop");
        let cargo = std::fs::read_to_string(dir.join("Cargo.toml")).unwrap();
        assert!(cargo.contains("name = \"frog_hop\"") && cargo.contains("[workspace]"), "standalone outside the monorepo");
        assert!(cargo.contains(&format!("maimbrain = {{ git = \"{SDK_GIT}\" }}")));
        assert!(dir.join("icon.png").is_file() && dir.join("src/sim.rs").is_file());
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn three_d_with_an_explicit_id_and_creator() {
        let root = scratch("3d");
        let dir = root.join("sky");
        new_game(&dir, &Options { three_d: true, id: Some("dev.example.sky"), creator: Some("@ada"), ..opts() }).unwrap();
        let m = read_manifest(&dir);
        assert_eq!((m.id.as_str(), m.creator.as_str(), m.name.as_str()), ("dev.example.sky", "@ada", "Sky"));
        assert!(m.has_stdlib("mb3d") && m.has_stdlib("mb2d"));
        assert!(dir.join("src/scene.rs").is_file());
        assert!(!std::fs::read_to_string(dir.join("src/lib.rs")).unwrap().contains("NAME"));
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn signed_in_uses_the_namespace_and_bad_ids_fail_before_writing() {
        let root = scratch("in");
        let dir = root.join("pop");
        new_game(&dir, &Options { who: Some(("ada_l", "com.maimbrain.ada-l")), ..opts() }).unwrap();
        let m = read_manifest(&dir);
        assert_eq!((m.id.as_str(), m.creator.as_str()), ("com.maimbrain.ada-l.pop", "@ada_l"));
        let bad = root.join("bad");
        assert!(new_game(&bad, &Options { id: Some("Not An Id"), ..opts() }).is_err());
        assert!(!bad.exists());
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn kits_are_found_by_name_or_alias_and_listed() {
        assert!(!KITS.is_empty(), "build.rs found no kits");
        for k in KITS {
            assert!(!k.summary.is_empty() && k.summary.len() <= 80, "{}: kit.toml summary", k.name);
            assert!(!k.tech.is_empty(), "{}: kit.toml tech", k.name);
            assert!(std::ptr::eq(find_kit(k.name).unwrap(), k));
            assert!(std::ptr::eq(find_kit(&k.name.to_uppercase().replace('-', "_")).unwrap(), k));
            assert!(kit_list().contains(k.summary));
        }
        for (alias, kit) in KIT_ALIASES {
            if let Some(k) = find_kit(kit) {
                assert!(std::ptr::eq(find_kit(alias).unwrap(), k), "{alias}");
            }
        }
        assert!(find_kit("chess").is_none());
        let err = new_game(&scratch("nokit").join("x"), &Options { kit: Some("chess"), ..opts() }).unwrap_err();
        assert!(err.contains("no kit called") && err.contains(KITS[0].name));
        assert!(new_game(&scratch("kit3d").join("x"), &Options { kit: Some(KITS[0].name), three_d: true, ..opts() }).is_err());
    }

    /// Every kit becomes a self-contained game: its crate name and SDK path
    /// rewritten, the manifest valid, the helper scripts in tools/.
    #[test]
    fn every_kit_scaffolds_a_standalone_game() {
        let root = scratch("kits");
        for k in KITS {
            let dir = root.join(format!("my_{}", k.name.replace('-', "_")));
            new_game(&dir, &Options { kit: Some(k.name), id: Some("dev.example.kitgame"), creator: Some("ci"), ..opts() }).unwrap();
            let m = read_manifest(&dir);
            assert_eq!((m.id.as_str(), m.creator.as_str()), ("dev.example.kitgame", "@ci"));
            let cargo = std::fs::read_to_string(dir.join("Cargo.toml")).unwrap();
            let crate_name = dir.file_name().unwrap().to_str().unwrap();
            assert!(cargo.contains(&format!("name = \"{crate_name}\"")), "{}: {cargo}", k.name);
            assert!(cargo.contains(SDK_GIT) && !cargo.contains("path = \"../") && cargo.contains("[workspace]"), "{}: {cargo}", k.name);
            assert!(dir.join("icon.png").is_file() && dir.join("src/lib.rs").is_file() && dir.join("DESIGN.md").is_file(), "{}", k.name);
            assert!(!dir.join("kit.toml").exists());
            for (path, _) in k.files {
                if is_text(path) {
                    let text = std::fs::read_to_string(dir.join(path)).unwrap();
                    assert!(!text.contains(&k.crate_name()), "{}: {path} still names {}", k.name, k.crate_name());
                }
            }
            if k.files.iter().any(|f| f.0.starts_with("tools/") && f.0.ends_with(".py")) {
                assert!(dir.join("tools/sfx.py").is_file() && dir.join("tools/pixel.py").is_file());
            }
        }
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn kit_cargo_toml_points_at_the_sdk_from_games() {
        let text = "[package]\nname = \"kit_tower_defense\"\n\n[dependencies]\n# `mb new --kit` rewrites this path.\nmaimbrain = { path = \"../../../../../sdk/maimbrain\", features = [\"physics2d\"] }\n";
        let out = kit_text("Cargo.toml", text, "kit_tower_defense", "castle");
        assert!(out.contains("name = \"castle\""));
        assert!(out.contains("maimbrain = { path = \"../../sdk/maimbrain\", features = [\"physics2d\"] }"));
        assert!(!out.contains("mb new --kit"));
        let standalone = standalone_cargo(&out);
        assert!(standalone.contains(&format!("maimbrain = {{ git = \"{SDK_GIT}\", features = [\"physics2d\"] }}")));
    }
}
