//! Generated by `mb art atlas sprites`: source rects in assets/sprites.png texels, [x, y, w, h].
#![allow(dead_code)]
pub const HERO_AIR: [f32; 4] = [2.0, 2.0, 528.0, 132.0];
pub const HERO_RUN: [f32; 4] = [532.0, 2.0, 528.0, 132.0];
pub const GULL: [f32; 4] = [1062.0, 2.0, 624.0, 96.0];
pub const SKIMMER: [f32; 4] = [1688.0, 2.0, 624.0, 96.0];
pub const DIRT: [f32; 4] = [2314.0, 2.0, 96.0, 96.0];
pub const BEE: [f32; 4] = [2412.0, 2.0, 192.0, 90.0];
pub const SUN: [f32; 4] = [2606.0, 2.0, 84.0, 84.0];
pub const CLOUD: [f32; 4] = [2692.0, 2.0, 432.0, 72.0];
pub const CRATE: [f32; 4] = [3126.0, 2.0, 72.0, 72.0];
pub const MOON: [f32; 4] = [3200.0, 2.0, 66.0, 66.0];
pub const LOG: [f32; 4] = [3268.0, 2.0, 192.0, 60.0];
pub const COIN: [f32; 4] = [3462.0, 2.0, 288.0, 48.0];
pub const GRASS: [f32; 4] = [3752.0, 2.0, 48.0, 48.0];
