//! Generated by `mb art atlas cast`: source rects in assets/cast.png texels, [x, y, w, h].
#![allow(dead_code)]
pub const P_BLUE: [f32; 4] = [2.0, 2.0, 128.0, 128.0];
pub const P_CORAL: [f32; 4] = [132.0, 2.0, 128.0, 128.0];
pub const P_GREEN: [f32; 4] = [262.0, 2.0, 128.0, 128.0];
pub const P_ORANGE: [f32; 4] = [2.0, 132.0, 128.0, 128.0];
pub const P_PINK: [f32; 4] = [132.0, 132.0, 128.0, 128.0];
pub const P_PURPLE: [f32; 4] = [262.0, 132.0, 128.0, 128.0];
pub const P_YELLOW: [f32; 4] = [2.0, 262.0, 128.0, 128.0];
pub const RAINBOW: [f32; 4] = [132.0, 262.0, 128.0, 128.0];
pub const ROCK: [f32; 4] = [262.0, 262.0, 128.0, 128.0];
