//! Generated by `mb art atlas sprites`: source rects in assets/sprites.png texels, [x, y, w, h].
#![allow(dead_code)]
pub const BOSS: [f32; 4] = [2.0, 2.0, 320.0, 256.0];
pub const BULB: [f32; 4] = [324.0, 2.0, 128.0, 128.0];
pub const PIP: [f32; 4] = [2.0, 260.0, 128.0, 128.0];
pub const SPINNER: [f32; 4] = [132.0, 260.0, 128.0, 128.0];
pub const SWOOPER: [f32; 4] = [2.0, 390.0, 448.0, 112.0];
pub const DARTER: [f32; 4] = [2.0, 504.0, 96.0, 96.0];
pub const JELLY: [f32; 4] = [100.0, 504.0, 96.0, 96.0];
pub const HAND: [f32; 4] = [198.0, 504.0, 64.0, 64.0];
pub const HEART: [f32; 4] = [264.0, 504.0, 64.0, 64.0];
pub const PW_MAGNET: [f32; 4] = [330.0, 504.0, 64.0, 64.0];
pub const PW_SHIELD: [f32; 4] = [396.0, 504.0, 64.0, 64.0];
pub const PW_SPREAD: [f32; 4] = [2.0, 602.0, 64.0, 64.0];
pub const GEM: [f32; 4] = [68.0, 602.0, 48.0, 48.0];
