//! `mb art atlas`: packs PNGs into one atlas (fewer images to load and
//! bind: mb2d allows 128) and writes a Rust module of source rects in the
//! same shape as the skill's pixel.py: `pub const HERO: [f32; 4] = [x, y, w, h];`.

use std::path::{Path, PathBuf};

use super::img::Image;

pub struct Packed {
    pub width: u32,
    pub height: u32,
    /// (name, x, y, w, h)
    pub rects: Vec<(String, u32, u32, u32, u32)>,
}

/// Shelf packing, tallest first, with `pad` clear texels between items; tries
/// several widths and keeps the smallest area.
pub fn pack(sizes: &[(String, u32, u32)], pad: u32) -> Packed {
    let mut order: Vec<usize> = (0..sizes.len()).collect();
    order.sort_by_key(|&i| (std::cmp::Reverse(sizes[i].2), std::cmp::Reverse(sizes[i].1), sizes[i].0.clone()));
    let widest = sizes.iter().map(|s| s.1).max().unwrap_or(1) + 2 * pad;
    let mut best: Option<Packed> = None;
    let mut width = widest.next_power_of_two().max(64);
    while width <= 4096 {
        let (mut x, mut y, mut shelf) = (pad, pad, 0);
        let mut rects = Vec::new();
        for &i in &order {
            let (name, w, h) = &sizes[i];
            if x + w + pad > width {
                x = pad;
                y += shelf + pad;
                shelf = 0;
            }
            rects.push((name.clone(), x, y, *w, *h));
            x += w + pad;
            shelf = shelf.max(*h);
        }
        let height = y + shelf + pad;
        if height <= 4096 && best.as_ref().is_none_or(|b| (width as u64 * height as u64) < (b.width as u64 * b.height as u64)) {
            best = Some(Packed { width, height, rects });
        }
        width *= 2;
    }
    best.unwrap_or(Packed { width: 0, height: 0, rects: Vec::new() })
}

fn const_name(stem: &str) -> String {
    let mut s: String = stem.chars().map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_uppercase() } else { '_' }).collect();
    if s.starts_with(|c: char| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}

pub fn run(game: &Path, name: &str, inputs: &[PathBuf], pad: u32, trim: bool, rust: Option<&Path>, remove: bool) -> Result<(), String> {
    let mut files: Vec<PathBuf> = inputs.iter().map(|p| if p.is_absolute() || p.exists() { p.clone() } else { game.join(p) }).collect();
    if files.is_empty() {
        // Every generated sprite and UI PNG in assets/.
        for e in std::fs::read_dir(game.join("assets")).map_err(|e| format!("{}: {e}", game.join("assets").display()))?.flatten() {
            let p = e.path();
            if p.extension().is_some_and(|x| x == "png")
                && let Ok(sc) = super::read_sidecar(&p)
                && matches!(sc.recipe["kind"].as_str(), Some("sprite") | Some("ui"))
            {
                files.push(p);
            }
        }
        files.sort();
    }
    let out_png = game.join("assets").join(format!("{name}.png"));
    files.retain(|f| f != &out_png);
    if files.is_empty() {
        return Err("nothing to pack: pass PNG files, or generate sprites first".into());
    }
    let mut items = Vec::new();
    for f in &files {
        let im = Image::decode(&std::fs::read(f).map_err(|e| format!("{}: {e}", f.display()))?).map_err(|e| format!("{}: {e}", f.display()))?;
        let stem = f.file_stem().map(|s| s.to_string_lossy().to_string()).unwrap_or_default();
        let (offset, full) = ((0, 0), (im.w, im.h));
        let (im, offset) = if trim {
            match im.content_bbox(0) {
                Some((x, y, w, h)) => (im.crop(x, y, w, h), (x, y)),
                None => (im, offset),
            }
        } else {
            (im, offset)
        };
        items.push((stem, im, offset, full));
    }
    let sizes: Vec<(String, u32, u32)> = items.iter().map(|(n, im, _, _)| (n.clone(), im.w, im.h)).collect();
    let packed = pack(&sizes, pad);
    if packed.width == 0 {
        return Err("these images don't fit in a 4096×4096 atlas".into());
    }
    let mut sheet = Image::new(packed.width, packed.height, [0; 4]);
    for (n, x, y, _, _) in &packed.rects {
        let im = &items.iter().find(|i| &i.0 == n).unwrap().1;
        sheet.blit(im, *x, *y);
    }
    let png = sheet.encode_png();
    std::fs::write(&out_png, &png).map_err(|e| format!("{}: {e}", out_png.display()))?;
    let mut lines =
        vec![format!("//! Generated by `mb art atlas {name}`: source rects in assets/{name}.png texels, [x, y, w, h]."), "#![allow(dead_code)]".to_string()];
    for (n, x, y, w, h) in &packed.rects {
        let c = const_name(n);
        lines.push(format!("pub const {c}: [f32; 4] = [{x}.0, {y}.0, {w}.0, {h}.0];"));
        if trim {
            let (_, _, off, full) = items.iter().find(|i| &i.0 == n).unwrap();
            lines.push(format!("/// Where the trimmed rect sits in the original {}×{} image.", full.0, full.1));
            lines.push(format!("pub const {c}_OFFSET: [f32; 2] = [{}.0, {}.0];", off.0, off.1));
            lines.push(format!("pub const {c}_SIZE: [f32; 2] = [{}.0, {}.0];", full.0, full.1));
        }
    }
    let rust_path = rust.map(Path::to_path_buf).unwrap_or_else(|| game.join("src").join(format!("{name}.rs")));
    if let Some(d) = rust_path.parent() {
        std::fs::create_dir_all(d).map_err(|e| e.to_string())?;
    }
    std::fs::write(&rust_path, lines.join("\n") + "\n").map_err(|e| format!("{}: {e}", rust_path.display()))?;
    // Provenance: the atlas lists what it was packed from.
    let sources: Vec<serde_json::Value> = files
        .iter()
        .map(|f| {
            let sc = super::read_sidecar(f).ok();
            serde_json::json!({
                "file": super::rel(f, game),
                "provider": sc.as_ref().map(|s| s.provider.clone()),
                "model": sc.as_ref().map(|s| s.model.clone()),
                "prompt": sc.as_ref().map(|s| s.prompt.clone()),
                "seed": sc.as_ref().map(|s| s.seed),
                "date": sc.as_ref().map(|s| s.date.clone()),
            })
        })
        .collect();
    let side = super::sidecar_path(&out_png);
    std::fs::write(
        &side,
        serde_json::to_string_pretty(&serde_json::json!({
            "generator": format!("mb {} art atlas", env!("CARGO_PKG_VERSION")),
            "date": super::now_utc(),
            "packed_from": sources,
            "output_sha256": super::sha256_hex(&png),
        }))
        .unwrap()
            + "\n",
    )
    .map_err(|e| e.to_string())?;
    if remove {
        for f in &files {
            let _ = std::fs::remove_file(f);
            let _ = std::fs::remove_file(super::sidecar_path(f));
        }
    }
    eprintln!(
        "packed {} images into {} ({}×{}, {} KB) and wrote {}",
        files.len(),
        out_png.display(),
        packed.width,
        packed.height,
        png.len().div_ceil(1024),
        rust_path.display()
    );
    if !remove {
        eprintln!("the source PNGs are still in assets/ and would ship too: delete them (or pass --remove-inputs) once the game draws from the atlas");
    }
    println!("{}", out_png.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn packs_without_overlap_with_padding() {
        let sizes: Vec<(String, u32, u32)> = (0..12).map(|i| (format!("s{i}"), 30 + i * 7, 20 + (i * 13) % 50)).collect();
        let p = pack(&sizes, 2);
        assert!(p.width <= 4096 && p.height <= 4096);
        for (i, a) in p.rects.iter().enumerate() {
            assert!(a.1 >= 2 && a.2 >= 2 && a.1 + a.3 + 2 <= p.width && a.2 + a.4 + 2 <= p.height);
            for b in &p.rects[i + 1..] {
                let apart = a.1 + a.3 + 2 <= b.1 || b.1 + b.3 + 2 <= a.1 || a.2 + a.4 + 2 <= b.2 || b.2 + b.4 + 2 <= a.2;
                assert!(apart, "{a:?} overlaps {b:?}");
            }
        }
    }

    #[test]
    fn rust_names() {
        assert_eq!(const_name("hero-walk"), "HERO_WALK");
        assert_eq!(const_name("1up"), "_1UP");
    }
}
